// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7TEexQcOOIwyJxsc6870oFRmtXzcmTH4',
    appId: '1:387881965254:web:fd29bd57f0c39df373e9c7',
    messagingSenderId: '387881965254',
    projectId: 'hotspot-54ded',
    authDomain: 'hotspot-54ded.firebaseapp.com',
    storageBucket: 'hotspot-54ded.firebasestorage.app',
    measurementId: 'G-809CN2B1NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6ziCVWHMjtig2C1mGsLznmYaDzC1TZFw',
    appId: '1:387881965254:android:66694ab77253de5f73e9c7',
    messagingSenderId: '387881965254',
    projectId: 'hotspot-54ded',
    storageBucket: 'hotspot-54ded.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx4sUCsDN8-H8OP1BekClNGL2w_osy6oc',
    appId: '1:387881965254:ios:7962a4f20ae657a473e9c7',
    messagingSenderId: '387881965254',
    projectId: 'hotspot-54ded',
    storageBucket: 'hotspot-54ded.firebasestorage.app',
    iosBundleId: 'com.example.hotspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx4sUCsDN8-H8OP1BekClNGL2w_osy6oc',
    appId: '1:387881965254:ios:7962a4f20ae657a473e9c7',
    messagingSenderId: '387881965254',
    projectId: 'hotspot-54ded',
    storageBucket: 'hotspot-54ded.firebasestorage.app',
    iosBundleId: 'com.example.hotspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7TEexQcOOIwyJxsc6870oFRmtXzcmTH4',
    appId: '1:387881965254:web:3f6dc81a2c04bd3973e9c7',
    messagingSenderId: '387881965254',
    projectId: 'hotspot-54ded',
    authDomain: 'hotspot-54ded.firebaseapp.com',
    storageBucket: 'hotspot-54ded.firebasestorage.app',
    measurementId: 'G-VVHNMX4J33',
  );
}
